# Form implementation generated from reading ui file 'src/vista/main_window.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuARCHIVO = QtWidgets.QMenu(parent=self.menubar)
        self.menuARCHIVO.setObjectName("menuARCHIVO")
        self.menuCALCULO_DE_AREAS = QtWidgets.QMenu(parent=self.menubar)
        self.menuCALCULO_DE_AREAS.setObjectName("menuCALCULO_DE_AREAS")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSalir = QtGui.QAction(parent=MainWindow)
        self.actionSalir.setObjectName("actionSalir")
        self.actionCirculo = QtGui.QAction(parent=MainWindow)
        self.actionCirculo.setObjectName("actionCirculo")
        self.actionTriangulo = QtGui.QAction(parent=MainWindow)
        self.actionTriangulo.setObjectName("actionTriangulo")
        self.actionRectangulo = QtGui.QAction(parent=MainWindow)
        self.actionRectangulo.setObjectName("actionRectangulo")
        self.actionCuadrado = QtGui.QAction(parent=MainWindow)
        self.actionCuadrado.setObjectName("actionCuadrado")
        self.menuARCHIVO.addAction(self.actionSalir)
        self.menuCALCULO_DE_AREAS.addAction(self.actionCirculo)
        self.menuCALCULO_DE_AREAS.addAction(self.actionTriangulo)
        self.menuCALCULO_DE_AREAS.addAction(self.actionRectangulo)
        self.menuCALCULO_DE_AREAS.addAction(self.actionCuadrado)
        self.menubar.addAction(self.menuARCHIVO.menuAction())
        self.menubar.addAction(self.menuCALCULO_DE_AREAS.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuARCHIVO.setTitle(_translate("MainWindow", "ARCHIVO"))
        self.menuCALCULO_DE_AREAS.setTitle(_translate("MainWindow", "CALCULO DE AREAS"))
        self.actionSalir.setText(_translate("MainWindow", "SALIR"))
        self.actionCirculo.setText(_translate("MainWindow", "CIRCULO"))
        self.actionTriangulo.setText(_translate("MainWindow", "TRIANGULO"))
        self.actionRectangulo.setText(_translate("MainWindow", "RECTANGULO"))
        self.actionCuadrado.setText(_translate("MainWindow", "CUADRADO"))
